---
title: "DA401 Suicide Risk"
author: "Jiayu Zhao"
date: "10/26/2022"
output:
  html_document:
    code_folding: hide
    theme: journal
    toc: yes
    toc_depth: 3
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data cleaning
```{r}
true20<- NSDUH_2020%>%
  filter(auinpyr == 1|auoptyr == 1)
true19<-PUF2019_100920 %>%
  filter(auinpyr == 1|auoptyr == 1)
true18<-PUF2018_100819 %>%
  filter(auinpyr == 1|auoptyr == 1)
true18$QUESTID2<-as.integer(true18$QUESTID2)
true19$QUESTID2<-as.integer(true19$QUESTID2)
SuicideRisk<-bind_rows(true20, true19, true18)

SR<-SuicideRisk %>% 
  dplyr::select(DSTHOP30, mhsuithk, mhsuipln, mhsuitry, K6SCMON, SMIPP_U, AUNMPSY2, AUNMPGE2, AUNMMED2, AUNMAHS2, AUNMRES2,
         AUNMSFA2, AUNMMEN2, AUNMTHE2, AUNMDOC2, AUNMCLN2, AUNMDTM2, AUNMOTO2, amdelt, ASDSOVL2, CATAG6, irmarit,
         irsex, IREDUHIGHST2, NEWRACE2, wrkdpstyr, income, ALCWD2SX, alcndmor)

val1 = c(83,91,93,94,97,98,99)  #value for the invalid data (unknow, no repsonse...)
SR <- as.data.frame(sapply(SR, function(x) replace(x, x %in% val1, 0)))
```

```{r}
#Combine treatment from multiple facilities into a single var
a<-SR
val2 = c(985,994,997,998,999)
a[7:18] <- sapply(a[7:18], function(x) replace(x, x %in% val2, 0))
a$inpatient<-rowSums(a[7:12])
a$outpatient <- rowSums(a[13:18])
```

## Risk Index

#### Suicide Risk Level (categorical)
```{r}
SR<-SR %>% mutate(risk_level = case_when(as.numeric(DSTHOP30 != 98 & DSTHOP30<3) + as.numeric(mhsuithk==1)+ 
                                           as.numeric(mhsuipln == 1) + as.numeric(mhsuitry == 1) +
                                           as.numeric(K6SCMON > 16) + as.numeric(SMIPP_U > 0.65) >= 3 ~"high",
                                         as.numeric(DSTHOP30 != 98 & DSTHOP30 == 3) + as.numeric(mhsuithk == 1) +
                                           as.numeric(mhsuipln == 1 | mhsuitry == 1) + 
                                           as.numeric(K6SCMON <= 16 & K6SCMON >= 8) + 
                                           as.numeric(SMIPP_U <= 0.65 & SMIPP_U > 0.3) >= 3 ~"moderate",
                                         as.numeric(DSTHOP30 != 98 & DSTHOP30>3) + as.numeric(K6SCMON < 8) +
                                           as.numeric(mhsuithk== 1 | mhsuipln == 1 | mhsuitry == 1) +
                                           as.numeric(SMIPP_U <= 0.3) >= 1 ~ "low"))
SR$risk_level[is.na(SR$risk_level)] <- "no"
```

#### Suicide Risk Score (continuous)
```{r}
a1<-a
a1<-a1[c(-7:-18)]
a1[c(7:11,13:18)] <- lapply(a1[c(7:11,13:18)], factor)

a1$K6SCMON = as.numeric(scale(a1$K6SCMON))
a1$DSTHOP30=as.numeric(factor(a1$DSTHOP30, levels = c(5,4,3,2,1), labels = c(1,2,3,4,5)))
a1 <- a1 %>% rowwise() %>%
  mutate(risk_score = sum(c_across(DSTHOP30:SMIPP_U)))
```

## Regression

#### ANOVA
```{r}
library(tidyverse)
library(ggpubr)
library(rstatix)

set.seed(123)
a1 %>% sample_n_by(ASDSOVL2, alcndmor, ALCWD2SX, income, wrkdpstyr, size = 1)

## Check Normality
normality <- lm(risk_score ~ ASDSOVL2*alcndmor*ALCWD2SX*income*wrkdpstyr*IREDUHIGHST2, data = a1)
# Create a QQ plot of residuals
ggqqplot(residuals(normality))
# Compute Shapiro-Wilk test of normality
shapiro_test(residuals(normality))

## Homogeneity of variance
a1 %>% levene_test(risk_score ~ ASDSOVL2*alcndmor*ALCWD2SX*income*wrkdpstyr**IREDUHIGHST2, data = a1)

# Test
res.aov <- a1 %>% anova_test(risk_score ~ ASDSOVL2*alcndmor*ALCWD2SX*income*wrkdpstyr*IREDUHIGHST2)
res.aov
```

#### Plots for Interactive Effects
```{r}
reg_interact<-lm(data = a1, risk_score ~ wrkdpstyr*IREDUHIGHST2 + ASDSOVL2*alcndmor*ALCWD2SX*IREDUHIGHST2)
summary(reg_interact)

interact_plot(reg_interact, pred = IREDUHIGHST2 , modx = wrkdpstyr)
interact_plot(reg_interact, pred = IREDUHIGHST2 , modx = ASDSOVL2)
cat_plot(reg_interact, pred =ASDSOVL2, modx = alcndmor, geom = "line")
```


